# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QWidget, QTableWidgetItem


class Show_table(QWidget):
    def __init__(self):
        super(Show_table, self).__init__()

    def setupUi(self, file_name, sheet, new_col=None, new_col_value=None):
        self.setObjectName("Form")
        self.resize(1920, 1080)
        self.tableWidget = QtWidgets.QTableWidget(self)
        self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1920, 1080))
        self.tableWidget.setObjectName("tableWidget")
        self.file_name = file_name
        self.new_col = new_col
        self.new_col_value = new_col_value
        #列宽填满
        self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.Stretch)
        #列宽自动适应
        # self.tableWidget.horizontalHeader().setSectionResizeMode(QtWidgets.QHeaderView.ResizeToContents)

        # 设置表格的行数和列数
        self.tableWidget.setRowCount(sheet.max_row)
        self.tableWidget.setColumnCount(sheet.max_column)

        # 填充表格数据
        for row in range(1, sheet.max_row + 1):
            for col in range(1, sheet.max_column + 1):
                cell_value = sheet.cell(row=row, column=col).value
                if cell_value is not None:
                    item = QTableWidgetItem(str(cell_value))
                    self.tableWidget.setItem(row - 1, col - 1, item)
        if self.new_col:
            self.tableWidget.setColumnCount(sheet.max_column + 1)  # 加上新列
            # print(self.new_col, sheet.max_column, self.new_col_value, len(self.new_col_value))
            # 添加新的列项和值到表格中
            self.tableWidget.setItem(0, sheet.max_column, QTableWidgetItem(self.new_col))
            for i in range(len(self.new_col_value)):
                item = QTableWidgetItem(str(self.new_col_value[i]))
                self.tableWidget.setItem(i + 1, sheet.max_column, item)  # 添加到新列的最后一列
        # 设置第一行的自动调整模式为Fixed
        self.tableWidget.verticalHeader().setSectionResizeMode(0, QtWidgets.QHeaderView.Fixed)
        self.retranslateUi()
        QtCore.QMetaObject.connectSlotsByName(self)
        self.showMaximized()

    def retranslateUi(self):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(self.file_name)
