# -*- coding: utf-8 -*-
import sys

# Form implementation generated from reading ui file 'T_inspect_table.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt
from PyQt5.QtGui import QBrush, QColor
from PyQt5.QtWidgets import QApplication, QMainWindow


class T_inspect_table(QtWidgets.QWidget):
    try:
        def __init__(self):
            super(T_inspect_table, self).__init__()

        def setupUi(self, inspection_entry, confidence_entry, selected_classfication_items, selected_inspect_items,
                    T_result):
            self.setObjectName("单样本T检验")
            self.resize(810, 130)
            self.centralwidget = QtWidgets.QWidget(self)
            self.centralwidget.setObjectName("centralwidget")
            self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
            self.tableWidget.setGeometry(QtCore.QRect(0, 0, 1020, 400))
            self.tableWidget.setObjectName("tableWidget")
            self.tableWidget.setColumnCount(8)
            self.tableWidget.setRowCount(4)

            self.label = QtWidgets.QLabel(self.centralwidget)
            self.label.setGeometry(QtCore.QRect(500, 0, 91, 41))
            self.label.setObjectName("label")

            row_name = "检验值=" + str(inspection_entry)
            self.tableWidget.setSpan(0, 0, 1, 8)
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(0, 0, item)
            item.setTextAlignment(Qt.AlignCenter)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            row_name = selected_classfication_items
            self.tableWidget.setSpan(1, 0, 2, 2)
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(1, 0, item)
            item.setTextAlignment(Qt.AlignBottom)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            self.tableWidget.setSpan(1, 2, 2, 1)
            row_name = "t"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(1, 2, item)
            item.setTextAlignment(Qt.AlignBottom)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            self.tableWidget.setSpan(1, 3, 2, 1)
            row_name = "自由度"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(1, 3, item)
            item.setTextAlignment(Qt.AlignBottom)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            self.tableWidget.setSpan(1, 4, 2, 1)
            row_name = "Sig.(双尾）"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(1, 4, item)
            item.setTextAlignment(Qt.AlignBottom)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            self.tableWidget.setSpan(1, 5, 2, 1)
            row_name = "平均值差值"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(1, 5, item)
            item.setTextAlignment(Qt.AlignBottom)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            row_name = "插值" + str(confidence_entry * 100) + "%置信区间"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(1, 6, item)
            item.setTextAlignment(Qt.AlignCenter)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            self.tableWidget.setSpan(1, 6, 1, 2)
            row_name = "下限"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(2, 6, item)
            item.setTextAlignment(Qt.AlignCenter)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            row_name = "上限"
            item = QtWidgets.QTableWidgetItem(row_name)
            self.tableWidget.setItem(2, 7, item)
            item.setTextAlignment(Qt.AlignCenter)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            item = QtWidgets.QTableWidgetItem(str(T_result[6]))
            self.tableWidget.setItem(3, 0, item)
            item.setTextAlignment(Qt.AlignCenter)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            item = QtWidgets.QTableWidgetItem(selected_inspect_items)
            self.tableWidget.setItem(3, 1, item)
            item.setTextAlignment(Qt.AlignCenter)
            item.setForeground(QBrush(QColor(0, 0, 255)))

            item = QtWidgets.QTableWidgetItem(str(T_result[0]))
            self.tableWidget.setItem(3, 2, item)
            item.setTextAlignment(Qt.AlignCenter)

            item = QtWidgets.QTableWidgetItem(str(T_result[1]))
            self.tableWidget.setItem(3, 3, item)
            item.setTextAlignment(Qt.AlignCenter)

            item = QtWidgets.QTableWidgetItem(str(T_result[2]))
            self.tableWidget.setItem(3, 4, item)
            item.setTextAlignment(Qt.AlignCenter)

            item = QtWidgets.QTableWidgetItem(str(T_result[3]))
            self.tableWidget.setItem(3, 5, item)
            item.setTextAlignment(Qt.AlignCenter)

            item = QtWidgets.QTableWidgetItem(str(T_result[4]))
            self.tableWidget.setItem(3, 6, item)
            item.setTextAlignment(Qt.AlignCenter)

            item = QtWidgets.QTableWidgetItem(str(T_result[5]))
            self.tableWidget.setItem(3, 7, item)
            item.setTextAlignment(Qt.AlignCenter)

            self.retranslateUi(self)

        def retranslateUi(self, MainWindow):
            _translate = QtCore.QCoreApplication.translate
            MainWindow.setWindowTitle(_translate("MainWindow", "单样本T检验"))
            self.tableWidget.verticalHeader().setVisible(False)
            self.tableWidget.horizontalHeader().setVisible(False)
            self.label.setText(_translate("MainWindow", ""))
    except Exception as e:
        # 处理异常
        print("输出T检验表格异常：", str(e))
